services:
  - type: web
    name: image-caption-backend
    env: python
    buildCommand: ""
    startCommand: flask run --host=0.0.0.0 --port=10000
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: backend/app.py
